export const SET_USER = "SET_USER";
export const PAGE_TIMELINE = "PAGE_TIMELINE";
export const PAGE_USER_PROFILE = "PAGE_USER_PROFILE";
export const PAGE_SINGLE_TWEET = "PAGE_SINGLE_TWEET";
export const LIKES_MODAL = "LIKES_MODAL";
export const RETWEETS_MODAL = "RETWEETS_MODAL";